### ISSUE TITLE
Overhaul docs

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#295]
* [x] de-emphasize OStatus
 * [x] drop Atom feed mention entirely (#283)
 * [x] how to follow. [example for mastodon](https://indieweb.social/authorize_interaction?uri=@kongaloosh.com@kongaloosh.com)
 * [ ] how to not have www in domain: your site's BF redirects and home page need to not redirect to www. Or, #314!
 * [x] @-mentions from fediverse get converted to home page wms
 * [x] profile picture, name, etc come from homepage h-card
 * [x] HTML (eg links) in original posts is preserved and rendered ok in Mastodon ([example](https://indieweb.social/@snarfed.org@snarfed.org/109327939703730432))
 * [x] setting custom username with acct: u-url in representative h-card. Requested in #3, implemented in #27
 * [x] requires SSL, as a way to verify that you own the domain
 * [x] other people can search for just your domain in eg Mastodon search, no @domain@domain syntax needed

**Comment by aciccarello** [comment]
Trying to think of some possible language for the acct username piece. Here's a suggestion.

> ## How do I use a custom username?
> 
> Bridgy Fed uses your domain as both the username and domain (@example.com@example.com) by default. 
> 
> On your homepage, add a `<a class="u-url" href="acct:custom@example.com">` link to your representative [h-card](http://microformats.org/wiki/h-card) with an acct value matching your desired name.
> 
> ```html
> <span class="h-card">
>   <a class="p-name u-url" href="https://example.com">John Smith</a>
>   <a class="u-url" href="acct:custom@example.com"></a>
> </span>
> ```
> 
> Or more minimally
> ```html
> <a class="h-card" href="acct:custom@example.com">John Smith</a>, 
> ```
> 
> Note that clients like Mastodon may hide the domain so the default of @example.com@example.com appears as simply @example.com in mentions in posts.

**Comment by snarfed** [comment]
This is great, thank you for writing it!

**Comment by snarfed** [comment]
Deferring the www one to #314. The rest are done!
